config/routes.rb
Minmin::Application.routes.draw do
  get "share", to: "posts#share"

  resources :posts do
    post "search", on: :collection

  end

  root 'posts#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  POST_TYPES = [ :text, :photo, :quote, :link, :video ]
  validates_inclusion_of :post_type, in: POST_TYPES
  validates_uniqueness_of :slug

  before_validation :symbolize_usertype,:slugify_title
   
  def self.post_types
    POST_TYPES
  end

  protected
  def slugify_title
    self.slug = title.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end

  def symbolize_usertype
    self.post_type = self.post_type.to_sym if post_type
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("id desc").limit(30)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.published_at = DateTime.now if @post.published_at.blank?
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @posts = Post.where("'#{params[:search]}' = ANY (tags)
                        or  body like '%#{params[:search]}%'
                        or  title like '%#{params[:search]}%'
                      ")
               
    render :index
  end

  def share
    @post = Post.new(title: params[:t], body: "<p><a href=#{params[:u]}>#{params[:u]}</a></p>
                                                #{params[:s].html_safe}")
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.where(id: params[:id]).first
      @post = Post.where(slug: params[:id]).first if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      pre_params = params.require(:post).permit(:title, :body, :slug, :post_type, :published_at, :tags)
      pre_params[:tags] = pre_params[:tags].downcase.split( /, */ )
      pre_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def pretty_tags(post=nil)
    post ||= @post
    post.tags.map { |f| "##{f}" }.join(" ") if post and post.tags
  end

  def edit_tags
    @post.tags.map { |f| "#{f}" }.join(", ") if @post and @post.tags
  end

  def post_types_select
    Post.post_types.map { |p| [p.to_s.titleize, p ] }
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Minmin
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .row
        .col-xs-2
          %h1 ChaZiv
        .col-xs-2{style: "padding: 25px 0px 0px 0px;"}
          =form_tag  '/posts/search', method: :post do
            =text_field_tag "search", "", placeholder: "Search" , class: "form-control"
      = yield

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title
    %br/
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :body
    %br/
    = f.text_area :body, class: "form-control", rows: 5
  .form-group
    = f.label :post_type
    %br/
    = f.select :post_type, options_for_select(post_types_select, "link"), class: "form-control"

  .form-group
    = f.label :tags
    %br/
    = f.text_field :tags, value: edit_tags, class: "form-control"
  .form-group
    = f.submit "Post", class: "btn btn-primary"

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
.col-md-6.col-md-offset-3
  - @posts.each do |post|
    .panel.panel-default
      .panel-heading
        =link_to post.title, "posts/#{post.slug}"
      .panel-body
        = post.body.html_safe
        .row{style: "padding: 15px 5px 5px 0px;"}
          .col-md-10
            = pretty_tags(post)
          .col-md-2.text-right
            =post.published_at.strftime( "%m/%d/%Y") if post.published_at
        .row
          .col-md-4        
            = link_to 'Show', post
            = link_to 'Edit', edit_post_path(post)
            = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Post', new_post_path

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/share.html.haml
= render 'form'

app/views/posts/show.html.haml
.col-md-6.col-md-offset-3
  .panel.panel-default
    .panel-heading
      =link_to @post.title, "posts/#{@post.slug}"
    .panel-body
      = @post.body.html_safe
      .row{style: "padding: 15px 5px 5px 0px;"}
        .col-md-10
          = pretty_tags(@post)
        .col-md-2.text-right
          =@post.published_at.strftime( "%m/%d/%Y") if @post.published_at
      .row
        .col-md-4  
          = link_to 'Edit', edit_post_path(@post) 
          |
          = link_to 'All Posts', posts_path